### ISSUE TITLE
.WithVolumeMount - Login failed for user 'sa'

### ISSUE THREAD

**Issue by TheLever** [dotnet/aspire-samples#171] opened 2024-04-01 17:08 UTC
On 8 preview 4.24156.9, I am using .WithVolumeMount for a container Aspire spins up for me. In order to limit the number of projects, I took the code from the database migration sample and made it into a class I can call from my Program.cs in my service (other than that, the code is as is). I get "Login failed for user 'sa'". If I delete the volume, the service starts up, and things work. Next time I start up the service, I get the same "Login failed for use 'sa'".

What should I be looking at?

**Comment by DamianEdwards** [comment] 2024-04-01 18:43
Once you use a volume you need to use a stable password for the database. Make sure you're passing a stable password to the `AddSqlServer` method in your AppHost project.

**Comment by TheLever** [comment] 2024-04-01 19:51
Thanks for the reply. I believe I have that: I am using a secret from the app host's secret store and passing it to `AddSqlServer` as indicated. Still, it complains about the login failing.

**Comment by DamianEdwards** [comment] 2024-04-01 21:43
Does the sample work for you locally? Can you share the code after your refactoring?

**Comment by TheLever** [comment] 2024-04-02 04:55
Can you clarify which sample? The DatabaseMigration sample?

**Comment by DamianEdwards** [comment] 2024-04-02 14:44
The one you mentioned you took the code from. It's hard to diagnose issues without code that reproduces the problem. The VolumeMount and DatabaseMigrations sample both work for me so it would help if you could share your code somewhere. Perhaps fork this repo and update the DatabaseMigrations sample to match what you've done?

**Comment by TheLever** [comment] 2024-04-06 17:37
Hi! Sorry for the delay - real world problems needed my attention. I'll try to describe the repro steps to see this happen.

1) Create a normal aspire starter solution
2) InAppHost/Program.cs, add the following lines:
```c#
var sqlPwd = builder.Configuration["sqlpassword"];
// Check for null pwd has been omitted
var sql = builder.AddSqlServer("sql", sqlPwd)
    .WithVolumeMount("VolumeMount.sqlserver.data", "/var/opt/mssql")
    .AddDatabase("sqldata");
```
3) In ApiService/Program.cs, add:
```c#
builder.AddSqlServerClient("sqldata");
builder.AddSqlServerDbContext<BookDbContext>("sqldata");
...
// DbInitializer<T> is an adaptation of the DatabaseMigrations.MigrationService/ApiDbInitializer.cs
var dbInitializer = new DbInitializer<BookDbContext>(app.Services);
await dbInitializer.ExecuteAsync(CancellationToken.None);
```
4) Add DbInitializer.cs to the ApiService project:
```c#
public class DbInitializer<T>(IServiceProvider serviceProvider) where T : DbContext
{
    public async Task ExecuteAsync(CancellationToken cancellationToken)
    {
        try
        {
            using var scope = serviceProvider.CreateScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<T>();

            await EnsureDatabaseAsync(dbContext, cancellationToken);
            await RunMigrationAsync(dbContext, cancellationToken);
        }
        catch (Exception ex)
        {
            throw;
        }
    }
        
    private static async Task EnsureDatabaseAsync(T dbContext, CancellationToken cancellationToken)
    {
        var dbCreator = dbContext.GetService<IRelationalDatabaseCreator>();

        var strategy = dbContext.Database.CreateExecutionStrategy();
        await strategy.ExecuteAsync(async () =>
        {
            // Create the database if it does not exist.
            // Do this first so there is then a database to start a transaction against.
            // Exception is thrown here: Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
            if (!await dbCreator.ExistsAsync(cancellationToken).ConfigureAwait(false))
            {
                await dbCreator.CreateAsync(cancellationToken).ConfigureAwait(false);
            }
        }).ConfigureAwait(false);
    }
    
    private static async Task RunMigrationAsync(T dbContext, CancellationToken cancellationToken)
    {
        var strategy = dbContext.Database.CreateExecutionStrategy();
        await strategy.ExecuteAsync(async () =>
        {
            // Run migration in a transaction to avoid partial migration if it fails.
            var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            await using var _ = transaction.ConfigureAwait(false);
            await dbContext.Database.MigrateAsync(cancellationToken).ConfigureAwait(false);
            await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
        }).ConfigureAwait(false);
    }
}
```

**Comment by DamianEdwards** [comment] 2024-04-15 22:04
@TheLever I adapted your example for the latest updates in preview.4 and preview.5 and I can't reproduce the issue. If you call `.WithDataVolume()` to create the volume for the SQL Server container, and pass a stable password to the SQL resource via a parameter resource (see below), I see the SQL container go through its lengthy initialization process on the first run, and then no subsequent runs it starts up quickly without any issue that I can see.

```csharp
var builder = DistributedApplication.CreateBuilder(args);

// Do not do this, put the value in user secrets instead
builder.Configuration["Parameters:sqlpassword"] = "P@$$w0rd1";

var sqlpassword = builder.AddParameter("sqlpassword", secret: true);
var sql = builder.AddSqlServer("sql", sqlpassword)
    .WithDataVolume()
    .AddDatabase("sqldata");

var apiService = builder.AddProject<Projects.AspireApp47_ApiService>("apiservice")
    .WithReference(sql);

builder.AddProject<Projects.AspireApp47_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(apiService);

builder.Build().Run();
```

I'm going to close this as no-repro but feel free to re-open with more information if you have it.

**Closed by DamianEdwards** 2024-04-15 22:04 UTC
