### ISSUE TITLE
Missing trace spans

### ISSUE THREAD

**Issue by liammclennan** [dotnet/aspire-samples#105] opened 2024-01-31 00:23 UTC
When viewing traces generated by the eShopLite example I notice that some spans are missing, and hence the visualization can't generate the correct hierarchy. In the screenshot below I've drawn stylish arrows where each missing span should be. 

![image](https://github.com/dotnet/aspire-samples/assets/271514/7a2acabc-9d16-42c2-85da-ea7e61179880)

The first span in the visualization has a parent span id referencing a span that is not there. The final two spans (`catalogservice GET` and `catalogdbmanager GET`) are rendered as top-level spans (spans with no parent) which makes no sense. This is happening because they too have parent spans that don't exist. 

At first I thought this was happening because there was one missing root span for the trace, possibly from the browser, but the three missing parent spans are all different. 

Thanks for considering this issue.

**Comment by davidfowl** [comment] 2024-01-31 15:25
cc @JamesNK

**Comment by JamesNK** [comment] 2024-02-01 05:15
I tested it out and I see a `HTTP GET /` on all endpoints when Aspire starts up.

@davidfowl This is from the workaround required to get the proxy working introduced just as P2 shipped, correct?

**Comment by davidfowl** [comment] 2024-02-01 05:26
That's right. This will be gone in preview 3

**Comment by JamesNK** [comment] 2024-02-01 05:33
@liammclennan Thanks for reporting. This is a temporary bug in tracing caused by a fix to another issue. It's fixed in the next version.

**Closed by JamesNK** 2024-02-01 05:33 UTC
