### ISSUE TITLE
[WebToolsE2E] Build and run AspireShop.sln, catalogdbmanager fails to start with error Npgsql.PostgresException (0x80004005): 28000: no pg_hba.conf entry for host "172.17.0.1"

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire-samples#185] opened 2024-04-08 15:36 UTC
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 [latest build, includes Aspire 8.0.0-preview.5.24201.12]
3. Apply NuGet Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**
1. Clone aspire-samples repo, checkout preview.5 branch
2. Update NuGet.config to use the correct feeds
3. Open samples\AspireShop.sln
4. Build and run (Ctrl+F5)

**ACTUAL**
Catalogdbmanager fails to start

![image](https://github.com/dotnet/aspire-samples/assets/8246794/47552b80-daaf-4992-b9c9-cbcf5ca7a024)

![image](https://github.com/dotnet/aspire-samples/assets/8246794/9e51c409-a1c4-4c20-bffc-0d97f275bbe6)

![image](https://github.com/dotnet/aspire-samples/assets/8246794/dd57acf7-e058-4d10-8922-191335301a63)

```
2024-04-08T15:34:56.6311749 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:50173/
2024-04-08T15:34:56.6461021 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:50174/
2024-04-08T15:34:56.6474960 info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2024-04-08T15:34:56.6500708 info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
2024-04-08T15:34:56.6503202 info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Repos\dotnet\aspire-samples\samples\AspireShop\AspireShop.CatalogDbManager
2024-04-08T15:34:58.4683748 fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      Npgsql.PostgresException (0x80004005): 28000: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "catalogdb", no encryption
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.Internal.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
         at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.UnpooledDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrationsAsync(CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<<ExecuteAsync>b__4_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at AspireShop.CatalogDbManager.CatalogDbInitializer.InitializeDatabaseAsync(CatalogDbContext dbContext, CancellationToken cancellationToken) in C:\Repos\dotnet\aspire-samples\samples\AspireShop\AspireShop.CatalogDbManager\CatalogDbInitializer.cs:line 29
         at AspireShop.CatalogDbManager.CatalogDbInitializer.ExecuteAsync(CancellationToken cancellationToken) in C:\Repos\dotnet\aspire-samples\samples\AspireShop\AspireShop.CatalogDbManager\CatalogDbInitializer.cs:line 19
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
        Exception data:
          Severity: FATAL
          SqlState: 28000
          MessageText: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "catalogdb", no encryption
          File: auth.c
          Line: 535
          Routine: ClientAuthentication
2024-04-08T15:34:58.4985558 crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      Npgsql.PostgresException (0x80004005): 28000: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "catalogdb", no encryption
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.Internal.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
         at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.UnpooledDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrationsAsync(CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<<ExecuteAsync>b__4_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at AspireShop.CatalogDbManager.CatalogDbInitializer.InitializeDatabaseAsync(CatalogDbContext dbContext, CancellationToken cancellationToken) in C:\Repos\dotnet\aspire-samples\samples\AspireShop\AspireShop.CatalogDbManager\CatalogDbInitializer.cs:line 29
         at AspireShop.CatalogDbManager.CatalogDbInitializer.ExecuteAsync(CancellationToken cancellationToken) in C:\Repos\dotnet\aspire-samples\samples\AspireShop\AspireShop.CatalogDbManager\CatalogDbInitializer.cs:line 19
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
        Exception data:
          Severity: FATAL
          SqlState: 28000
          MessageText: no pg_hba.conf entry for host "172.17.0.1", user "postgres", database "catalogdb", no encryption
          File: auth.c
          Line: 535
          Routine: ClientAuthentication
2024-04-08T15:34:58.5062921 info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

**EXPECTED**
Catalogdbmanager should start successfully

**Comment by davidfowl** [comment] 2024-04-08 15:40
@roji have you ever seen this error?

**Comment by roji** [comment] 2024-04-08 20:28
@davidfowl yeah, "no pg_hba.conf" means that there's no entry in the PostgreSQL (so db-side) authorization file for the given client IP/username/etc. combination. I'm not sure where the PostgreSQL configuration is coming from here - if this is a user-managed PG container, then it's up to them to make sure it's configured appropriately etc. Otherwise, if it's a local dev container set up by our Aspire component, it needs to be suitable open in terms of its pg_hba.conf... Can try to help further with more details/context.

**Comment by v-sherryfan** [comment] 2024-04-11 05:54
Unable to reproduce on 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12] using aspire-samples `main` branch.

**Comment by DamianEdwards** [comment] 2024-04-15 21:30
I couldn't repro this on a different machine with a fresh clone of dotnet/aspire-samples so I'm going to close this as no-repro. @balachir pls re-open if you have more info.

**Closed by DamianEdwards** 2024-04-15 21:30 UTC
Labels: area-samples
