### ISSUE TITLE
Access to the link whose services are not expose is denied and web page error after "azd deploy"

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#146] opened 2024-03-07 11:12 UTC
**Describe the issue:**
After running the `azd deploy` command, access to the links whose services are not expose is denied, and the error message is as follows:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/2dcf0777-76ab-44d0-9a88-9794be7924e9)
![image](https://github.com/dotnet/aspire-samples/assets/111940661/3e84e0b7-0eee-45ab-9456-e64c6ce04b98)
![image](https://github.com/dotnet/aspire-samples/assets/111940661/11438a78-e4e5-41c5-a35e-616c9a7b4a25)

And, there are some errors in the `frontend service` pages about some samples. 
- `AspireShop` sample frontend page error:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/46354881-588b-4d6f-a963-7abbccff4c1d)
- `AspireWithJavaScript` sample frontend page `react service` error: 
![image](https://github.com/dotnet/aspire-samples/assets/111940661/257d3e10-bacb-48cd-8938-d33d991a3f80)
- `AspireWithJavaScript` sample frontend page `angular service` error:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/3bbe313d-2c0c-4b98-9bc9-61734d61483c)

**Repro Steps:**
1. Clone code.
2. Cd to the sample folder.
3. Run command `azd init` -> choose use code from folder and accept the Aspire project -> When asking which services to expose, select any service with name like `web` , `client` , `frontend`,  `React`, `Angular` -> leave all other services unchecked.
4. Run command `azd up`.

**Environment:**
- Azd version: `azd version 1.7.0-beta.1-daily.3564805 (commit 81f3efd1049889762d01ca46a35630005b45f0b5)`
- Aspire version: `8.0.0-preview.4.24156.9`
- Samples: [AspireShop](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/AspireShop), [AspireWithDapr](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/AspireWithDapr), [AspireWithNode](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/AspireWithNode), [DatabaseContainers](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/DatabaseContainers), [AspireWithJavaScript](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/AspireWithJavaScript), `aspire-starter`

**Expected behavior:**
After `azd deploy`, all services links can load normally.

@rajeshkamal5050,  @vhvb1989 for notification.

**Comment by rajeshkamal5050** [comment] 2024-03-07 17:00
@Menghua1 expected that only `frontend` is exposed to public and all other services are internal.

cc @DamianEdwards for some of the `frontend` app related issues.

**Comment by DamianEdwards** [comment] 2024-03-20 00:32
I'd ask we open separate issues for each sample where there's a problem rather than this all up issue.

For the AspireShop sample, the errors in the browser console are caused by Blazor trying to do a redirect to the non-HTTPS endpoint which is blocked by the browser. This will be fixed in preview.5.

Adding @IEvangelist for the AspireWithJavascript sample issues.

**Comment by danmoseley** [comment] 2024-04-22 19:19
closing as noted above, please open individual issues if you didn't already.

**Closed by danmoseley** 2024-04-22 19:19 UTC
