### ISSUE TITLE
After upgrading .NET Aspire to `8.0.0-preview.3.24105.21` adding `AddDaprClient` fails with `InvalidOperationException`

### ISSUE THREAD

**Issue by rliberoff** [dotnet/aspire-samples#114] opened 2024-02-15 19:06 UTC
Hello,

After updating .NET Aspire to version `8.0.0-preview.3.24105.21`, the example that uses `AddDaprClient` throws an exception.

The error is:

`System.InvalidOperationException: 'This service descriptor is keyed. Your service provider may not support keyed services.'`

Steps to reproduce:

1 - Install latest version of .NET Aspire workload with `dotnet workload install aspire`.
2 - Check with `dotnet workload list` that .NET Aspire is version 8.0.0-preview.3.24105.21.
3 - Use example `AspireWithDapr`. 
4 - Execute the example. The exception is thrown after a few seconds.

Please help. Dapr support is fundamental for us,

Thank you.

**Comment by rliberoff** [comment] 2024-02-16 08:36
So, it seems that the issue is with library `Microsoft.Extensions.Http.Resilience`. The exception is thrown when that library when updating the dependency from version `8.1.0` to version `8.2.0`

**Comment by davidfowl** [comment] 2024-02-17 01:28
Can you provide the stack trace?

**Comment by matengo** [comment] 2024-02-21 13:39
Same here, for registering Mediatr:
![image](https://github.com/dotnet/aspire-samples/assets/5673886/4f529a30-0f6b-469b-b420-8d931a99cf31)

**Comment by matengo** [comment] 2024-02-21 13:47
Changed Microsoft.Extensions.Http.Resilience back to 8.0-0 solved that one..

**Comment by matengo** [comment] 2024-02-21 16:16
MediatR 12.1.1

**Comment by DamianEdwards** [comment] 2024-03-20 00:26
I'm unable to reproduce this issue since the update to preview.4 so closing out.

**Closed by DamianEdwards** 2024-03-20 00:26 UTC
Labels: area-dapr

**Comment by wbuck** [comment] 2024-04-20 17:53
I just tried using Aspire with our application and I'm receiving the same error with Aspire version `8.0.0-preview.5.24201.12`.

**Comment by davidfowl** [comment] 2024-04-20 17:59
The fix wasn't, in aspire, it was in the dapr client.

**Comment by wbuck** [comment] 2024-04-20 18:01
@davidfowl Ah OK, so I need to update dapr then?

**Comment by davidfowl** [comment] 2024-04-20 18:03
Yep

**Comment by wbuck** [comment] 2024-04-20 18:05
@davidfowl Yeah that worked! Thanks David!
