### ISSUE TITLE
--bind postgres is not working.

### ISSUE THREAD

**Issue by vishipayyallore** [dotnet/aspire-samples#47] opened 2023-11-27 07:46 UTC
# MANAULLY CREATE THE POSTGRES DATABASE BINDING
az containerapp update --name "catalogservice" --resource-group $RESOURCE_GROUP --bind postgres

# Execluded the --bind then the command started working
az containerapp create --name bindingdebug --image mcr.microsoft.com/k8se/services/postgres:14 `
    --environment $ENVIRONMENT --resource-group $RESOURCE_GROUP `
    --min-replicas 1 --max-replicas 1 --command "/bin/sleep" "infinity"

![image](https://github.com/dotnet/aspire-samples/assets/8255269/60f08f05-ce16-411a-900b-b2a42f858a82)

**Comment by DamianEdwards** [comment] 2023-11-28 23:43
I'm unable to reproduce this. Did you create the postgres service instance first?

**Comment by ahmelsayed** [comment] 2023-11-29 18:04
Looks like a bug in the cli with setting client type. For a workaround you can do `--bind postgres,clientType=none`

**Comment by vishipayyallore** [comment] 2023-11-29 18:09
> Looks like a bug in the cli with setting client type. For a workaround you can do `--bind postgres,clientType=none`

Thanks @ahmelsayed ; I will give it a retry this weekend. Many thanks.

**Regards,
Swamy**

**Comment by Greedygre** [comment] 2023-11-30 11:48
Hi @vishipayyallore 
This issue has been fixed and released in version `0.3.46` of `containerapp` extension.
You can update the extension with command, thanks!

```
az extension add -n containerapp --upgrade
```

**Comment by DamianEdwards** [comment] 2023-12-01 22:27
Closing this given the extension fix was published.

**Closed by DamianEdwards** 2023-12-01 22:27 UTC
Labels: area-samples, azure
