### ISSUE TITLE
[WebToolsE2E] When deploying Aspire-Samples/VolumeMount solution, running 'azd up' failed with error: Identifier "sqlserver" is declared multiple times. Remove or rename the duplicates.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire-samples#111] opened 2024-02-08 08:13 UTC
**REGRESSION INFO**: not repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [latest build, includes Aspire 8.0.0-preview.3.24105.21 ]
3. Apply NuGet Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo from preview.3 branch
2. Update NuGet.config to use the correct feeds
3. Open samples\VolumeMount.sln
4. Build
5. Right-click solution > Open Folder in File Explorer. In the opened folder, click any place > Open in Terminal 
6. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter. 
7. When running azd init choose to expose 'blazorweb' to the Internet
8. Run azd up to deploy to Azure

**ACTUAL**
Deployment failed: 
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: creating template: failed to compile bicep template: failed running bicep build: exit code: 1, stdout: , stderr: C:\Users\V-CAZH~1\AppData\Local\Temp\azd-infra918003068\main.bicep(26,18) : Error BCP104: The referenced module has errors.
C:\Users\ \AppData\Local\Temp\azd-infra918003068\resources.bicep(115,10) : Error BCP028: Identifier "sqlserver" is declared multiple times. Remove or rename the duplicates.
C:\Users\ \AppData\Local\Temp\azd-infra918003068\resources.bicep(185,10) : Error BCP028: Identifier "sqlserver" is declared multiple times. Remove or rename the duplicates.

![image](https://github.com/dotnet/aspire-samples/assets/82028229/5f38267e-ccba-49da-91c0-1ff3e43b50c6)

**EXPECTED**
Deployment can succeed.

**Comment by DamianEdwards** [comment] 2024-03-20 00:28
I can't reproduce this with latest Aspire preview.4 and AZD version 1.7.0 so closing out.

**Closed by DamianEdwards** 2024-03-20 00:28 UTC
Labels: area-samples
