### ISSUE TITLE
Fail to run "azd up" for sample "AspireWithNode"

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#178] opened 2024-04-03 10:37 UTC
**Describe the issue:**
Run the `azd up` command failed and the error messages are as follows:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/69b2e755-1128-4b53-886e-4449af4b2fa1)

**Repro Steps:**
1. Clone code.
2. Run command `cd samples/AspireWithNode`.
5. Run command `azd init` -> choose `Confirm and continue initializing my app` -> Enter environment name.
6. Run command `azd up`.

**Environment:**
- Azd version: `azd version 1.8.0-beta.1-daily.3661089 (commit d078aeb7cf1497aa7c8d629d2f6d434554e0cd9a)`
- Aspire version: `8.0.0-preview.5.24201.12`
- Sample: [AspireWithNode](https://github.com/dotnet/aspire-samples/tree/preview.5/samples/AspireWithNode)
- Branch: `preview.5`

**Expected behavior:**
`azd up` command can be executed successfully.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by rajeshkamal5050** [comment] 2024-04-03 22:30
Duplicate of https://github.com/Azure/azure-dev/issues/3649

**Closed** 2024-04-09 05:45 UTC
